### ISSUE TITLE
Unable to train model

### ISSUE THREAD

**Issue by Coder-Liuu** [Michedev/VAE_anomaly_detection#7]
I am a rookie, so I just want to train the model. I did not modify the dataset.py file. I ran the `train.py` file with the following command.
```
python train.py --input-size=100 --latent-size 10 --device cpu
```
but I got the following error. Can you tell me how to solve this problem? ?

```
Current run is terminating due to exception: not enough values to unpack (expected 2, got 1)
Engine run is terminating due to exception: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    train(model, opt, dloader, args.epochs, experiment_folder, args.device)
  File "train.py", line 37, in train
    trainer.run(dloader, epochs)
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 702, in run
    return self._internal_run()
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 775, in _internal_run
    self._handle_exception(e)
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 745, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 850, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/engine.py", line 833, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/__init__.py", line 102, in _update
    x, y = prepare_batch(batch, device=device, non_blocking=non_blocking)
  File "/home/liuyang/.local/lib/python3.7/site-packages/ignite/engine/__init__.py", line 37, in _prepare_batch
    x, y = batch
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Michedev** [comment]
Forgot to reply. Fixed
