### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Chadnon** [Michedev/VAE_anomaly_detection#8]
My dataset is changed to
```
def load_dataset() -> Dataset:
    # Overwrite this to load your dataset
    data = torch.rand(128, 6000)
    return TensorDataset(data, data)
```
Can you give me a code that can run directly? Thank you

Traceback (most recent call last):
  File "C:\Users\CDN\Desktop\VAE_anomaly_detection-master\train.py", line 89, in <module>
    train(model, opt, dloader, args.epochs, experiment_folder, args.device)
  File "C:\Users\CDN\Desktop\VAE_anomaly_detection-master\train.py", line 38, in train
    trainer.run(dloader, epochs)
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 702, in run
    return self._internal_run()
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 775, in _internal_run
    self._handle_exception(e)
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 469, in _handle_exception
    raise e
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 745, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 850, in _run_once_on_dataset
    self._handle_exception(e)
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 469, in _handle_exception
    raise e
  File "D:\Python_package\lib\site-packages\ignite\engine\engine.py", line 833, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "D:\Python_package\lib\site-packages\ignite\engine\__init__.py", line 104, in _update
    loss = loss_fn(y_pred, y)
TypeError: <lambda>() takes 1 positional argument but 2 were given

Process finished with exit code 1

**Comment by Michedev** [comment]
Will give a look during the day!

**Comment by Michedev** [comment]
fixed!
